/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package eu.bausov.kafkaavro.avdl;
@org.apache.avro.specific.AvroGenerated
public enum CompanySize implements org.apache.avro.generic.GenericEnumSymbol<CompanySize> {
  SMALL, MEDIUM, BIG;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"CompanySize\",\"namespace\":\"eu.bausov.kafkaavro.avdl\",\"symbols\":[\"SMALL\",\"MEDIUM\",\"BIG\"]}");

  public static org.apache.avro.Schema getClassSchema() {
    return SCHEMA$;
  }

  public org.apache.avro.Schema getSchema() {
    return SCHEMA$;
  }
}
